#spring.application.name=Spring-Security-Client
server:
   port:8080


  spring:
datasource:
  url:jdbc:mysql://localhost:3306/dbschool
  driver-class-name:com.mysql.cj.jdbc.Driver	
jpa:
 show-sql:true
hibernate:
   ddl-auto:update